apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node:14
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: nodejs-volume
          mountPath: /usr/src/app
      volumes:
      - name: nodejs-volume
        hostPath:
          path: /path/to/your/app
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer